nbgrader version 0.5.0
conda-forge/nbgrader-feedstock pull request #10
Opened 2017-07-08 20:41 UTC by jhamrick

This updates the feedstock for nbgrader version 0.5.0 and also fixes #1

2017-07-08 20:41 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2017-07-10 11:51 UTC, lgpage requested changes
please could you also re-render this with conda smithy 2.3.2

2017-07-10 11:51 UTC, lgpage commented on recipe/meta.yaml
> +  number: 1
build number should be 0

2017-07-10 14:38 UTC, jhamrick commented on recipe/meta.yaml
> +  number: 1
Good catch!

2017-07-10 14:38 UTC, jhamrick commented
> please could you also re-render this with conda smithy 2.3.2

Oh, yes. I tried doing that but must have forgotten to update conda smithy...

2017-07-10 14:47 UTC, jhamrick commented
Ok, done @lgpage !

2017-07-10 15:08 UTC, lgpage approved these changes

2017-07-10 22:17 UTC, merged